language: node_js
node_js: stable
branches:
  only:
  - source
before_install:
- openssl aes-256-cbc -K $encrypted_468d5cafde79_key -iv $encrypted_468d5cafde79_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- git config --global user.name "zhaochangqing"
- git config --global user.email "jingtingchangqing@gmail.com"
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
- npm install -g hexo-cli
- echo `hexo -v`
install:
- npm install
script:
- hexo clean
- hexo generate
after_success:
- cd ./public
- git init
- git add --all .
- git commit -m "Travis CI Auto Builder"
- git push --quiet --force https://$REPO_TOKEN@github.com/RMzcq/blog.git master
- chmod 600 ~/.ssh/id_rsa
- ssh root@45.78.62.19 -p 26301 -v -o StrictHostKeyChecking=no 'cd /www/wwwroot/blog && git reset --hard origin/master && git pull'
